-- Disable RLS on all tables since auth is removed
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE source_feeds DISABLE ROW LEVEL SECURITY;
ALTER TABLE reference_cards DISABLE ROW LEVEL SECURITY;
ALTER TABLE reference_card_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE autopilot_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE drafts DISABLE ROW LEVEL SECURITY;
ALTER TABLE insight_ratings DISABLE ROW LEVEL SECURITY;
ALTER TABLE draft_revisions DISABLE ROW LEVEL SECURITY;